routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\FeedController;
use App\Http\Controllers\FoxController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\FollowerController;
use App\Http\Controllers\FoxLikeController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('lang/{lang}', function ($lang) {
    app()->setLocale($lang);
    session()->put('locale', $lang);
    return redirect()->route('dashboard');
})->name('lang');

Route::get('', [DashboardController::class, 'index'])->name('dashboard');

Route::resource('fox', FoxController::class)
    ->except(['index', 'create', 'show'])
    ->middleware('auth');

Route::resource('fox', FoxController::class)->only(['show']);

Route::resource('fox.comments', CommentController::class)
    ->only(['store'])
    ->middleware('auth');

Route::resource('users', UserController::class)->only('show');
Route::resource('users', UserController::class)
    ->only('edit', 'update')
    ->middleware('auth');

Route::get('profile', [UserController::class, 'profile'])
    ->middleware('auth')
    ->name('profile');

Route::post('users/{user}/follow', [FollowerController::class, 'follow'])
    ->middleware('auth')
    ->name('users.follow');

Route::post('users/{user}/unfollow', [FollowerController::class, 'unfollow'])
    ->middleware('auth')
    ->name('users.unfollow');

Route::post('fox/{fox}/like', [FoxLikeController::class, 'like'])
    ->middleware('auth')
    ->name('foxx.like');

Route::post('fox/{fox}/unlike', [FoxLikeController::class, 'unlike'])
    ->middleware('auth')
    ->name('foxx.unlike');

Route::get('/feed', FeedController::class)
    ->middleware('auth')
    ->name('feed');

Route::get('/terms', function () {
    return view('terms');
})->name('terms');

Route::get('/admin', [AdminDashboardController::class, 'index'])
    ->middleware(['auth', 'can:admin'])
    ->name('admin.dashboard');

resources/views/foxx/shared/comments-box.blade.php
<div>
    <form action="{{ route('fox.comments.store', $fox->id) }}" method="POST">
        @csrf
        <div class="mb-3">
            <textarea name="content" class="fs-6 form-control" rows="1"></textarea>
        </div>
        <div>
            <button type="submit" class="btn btn-primary btn-sm"> Post Comment </button>
        </div>
    </form>

    <hr>
    @forelse ($fox->comments as $comment)
        <div class="d-flex align-items-start">
            <img style="width:35px" class="me-2 avatar-sm rounded-circle"
                src="{{ $comment->user->getImageURL() }}" alt="{{ $comment->user->name }}">
            <div class="w-100">
                <div class="d-flex justify-content-between">
                    <h6 class="">{{ $comment->user->name }}
                    </h6>
                    <small class="fs-6 fw-light text-muted">{{ $comment->created_at->diffForHumans() }}</small>
                </div>
                <p class="fs-6 mt-3 fw-light">
                    {{ $comment->content }}
                </p>
            </div>
        </div>
    @empty
        <p class="text-center mt-4">No Comments Found.</p>
    @endforelse
</div>

resources/views/foxx/shared/fox-card.blade.php
<div class="card">
    <div class="px-3 pt-4 pb-2">
        <div class="d-flex align-items-center justify-content-between">
            <div class="d-flex align-items-center">
                <img style="width:50px" class="me-2 avatar-sm rounded-circle"
                    src="{{ $fox->user->getImageURL() }}"
                    alt="{{ $fox->user->name }}">
                <div>
                    <h5 class="card-title mb-0"><a href="{{ route('users.show',$fox->user->id) }}">{{ $fox->user->name }}</a></h5>
                </div>
            </div>
            <div class="d-flex">
                <a href="{{ route('fox.show', $fox->id) }}"> View </a>
                @auth
                    @can('update', $fox)
                        <a class="mx-2" href="{{ route('fox.edit', $fox->id) }}"> Edit </a>
                        <form method="POST" action="{{ route('fox.destroy', $fox->id) }}">
                            @csrf
                            @method('delete')
                            <button class="ms-1 btn btn-danger btn-sm"> X </button>
                        </form>
                    @endcan
                @endauth
            </div>
        </div>
    </div>
    <div class="card-body">
        @if ($editing ?? false)
            <form action="{{ route('fox.update', $fox->id) }}" method="post">
                @csrf
                @method('put')
                <div class="mb-3">
                    <textarea name="content" class="form-control" id="content" rows="3">{{ $fox->content }}</textarea>
                    @error('content')
                        <span class="d-block fs-6 text-danger mt-2"> {{ $message }} </span>
                    @enderror
                </div>
                <div class="">
                    <button type="submit" class="btn btn-dark mb-2 btn-sm"> Update </button>
                </div>
            </form>
        @else
            <p class="fs-6 fw-light text-muted">
                {{ $fox->content }}
            </p>
        @endif
        <div class="d-flex justify-content-between">
            @include('foxx.shared.like-button')
            <div>
                <span class="fs-6 fw-light text-muted"> <span class="fas fa-clock"> </span>
                    {{ $fox->created_at->diffForHumans() }} </span>
            </div>
        </div>
        @include('foxx.shared.comments-box')
    </div>
</div>

resources/views/foxx/shared/like-button.blade.php
<div>
    @auth
        @if (Auth::user()->likesFox($fox))
            <form action="{{ route('foxx.unlike', $fox->id) }}" method="POST">
                @csrf
                <button type="submit" class="fw-light nav-link fs-6"> <span class="fas fa-heart me-1">
                    </span> {{ $fox->likes_count }} </button>
            </form>
        @else
            <form action="{{ route('foxx.like', $fox->id) }}" method="POST">
                @csrf
                <button type="submit" class="fw-light nav-link fs-6"> <span class="far fa-heart me-1">
                    </span> {{ $fox->likes_count }} </button>
            </form>
        @endif
    @endauth
    @guest
        <a href="{{ route('login') }}" class="fw-light nav-link fs-6"> <span class="far fa-heart me-1">
            </span> {{ $fox->likes_count }} </a>
    @endguest
</div>

resources/views/foxx/shared/submit-fox.blade.php
@auth
    <h4> Share yours ideas </h4>
    <div class="row">
        <form action="{{ route('fox.store') }}" method="post">
            @csrf
            <div class="mb-3">
                <textarea name="content" class="form-control" id="content" rows="3"></textarea>
                @error('content')
                    <span class="d-block fs-6 text-danger mt-2"> {{ $message }} </span>
                @enderror
            </div>
            <div class="">
                <button type="submit" class="btn btn-dark"> Share </button>
            </div>
        </form>
    </div>
@endauth
@guest
    <h4> {{ __('foxx.Login_To_Share') }} </h4>
@endguest